platform :ios, '9.0'
target 'XKFamilyDoctor' do
pod 'FMDB', '~> 2.6.2'
pod 'SDWebImage', '~> 3.8.2'
pod 'SDCycleScrollView', '~> 1.65'
pod 'AliPay', '~> 2.1.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'JSONKit', '~> 1.5pre'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'Masonry', '~> 1.0.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'Charts', '~> 3.0.2'
use_frameworks!

end
